- hosts: jellyfin
  become: no
  tasks:
    - name: Pull new changes from github
      ansible.builtin.git:
        repo: git@github.com:DanielEkstrom1/ApexBot.git
        dest: /home/danielekstrom/discordbot
        version: master
        update: yes
        force: no
    - name: Build and push to registery
      ansible.builtin.shell:
        cmd: docker buildx build --platform=linux/amd64,linux/arm64 -t baller/apexbot:latest . --push
        chdir: /home/danielekstrom/discordbot
- hosts: ubuntu
  become: no
  tasks:
    - name: Pull new container
      ansible.builtin.shell:
        chdir: /home/ubuntu/discbot
        cmd: docker-compose pull
    - name: Recreate container
      ansible.builtin.shell:
        chdir: /home/ubuntu/discbot
        cmd: docker-compose up -d